
services:
  backend:
    container_name: backend
    image: ntkitn/backend
    build: ./Backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/codeshare_db
    ports:
      - 8080:8080
    networks:
      - app_network

  frontend:
    container_name: frontend
    image: ntkitn/frontend
    build: ./compiler-online-app
    ports:
      - 4200:80
    networks:
      - app_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.6
  # Replace with the desired Keycloak version
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080 
    networks:
      - app_network
    command: 
      start-dev
      --import-realm
    volumes:
      - .backend/docker-keycloak-realm.json:/opt/keycloak/data/import/codeshare-realm.json

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: codeshare_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge