spring:
  security:
    oauth2:
      resourceserver:
<<<<<<< HEAD
=======
        opaque-token:
            introspection-uri: https://www.googleapis.com/
            clientId: CLIENT_ID
            clientSecret: CLIENT_SECRET
>>>>>>> 6d36d4719344c877c5f220ce544b428a3626b3fd
        jwt:
          issuer-uri: http://localhost:8081/realms/YOUR_REALM
          jwk-set-uri:  ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: codeshare-rest-api
      principle-attribute: preferred_username
