spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/codeshare
          jwk-set-uri:  ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: codeshare-rest-api
      principle-attribute: preferred_username