spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/codeshare
          jwk-set-uri:  http://keycloak:8080/realms/codeshare/protocol/openid-connect/certs



