
export const codeMirrorLanguages = [
  { "id": 45, "name": "Assembly (NASM 2.14.02)", "mode": "gas", "mime": "text/x-gas" },
  { "id": 46, "name": "Bash (5.0.0)", "mode": "shell", "mime": "application/x-sh" },
  { "id": 47, "name": "Basic (FBC 1.07.1)", "mode": "basic", "mime": "text/x-basic" },
  { "id": 104, "name": "C (Clang 18.1.8)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 75, "name": "C (Clang 7.0.1)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 76, "name": "C++ (Clang 7.0.1)", "mode": "clike", "mime": "text/x-c++src" },
  { "id": 103, "name": "C (GCC 14.1.0)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 105, "name": "C++ (GCC 14.1.0)", "mode": "clike", "mime": "text/x-c++src" },
  { "id": 48, "name": "C (GCC 7.4.0)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 52, "name": "C++ (GCC 7.4.0)", "mode": "clike", "mime": "text/x-c++src" },
  { "id": 49, "name": "C (GCC 8.3.0)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 53, "name": "C++ (GCC 8.3.0)", "mode": "clike", "mime": "text/x-c++src" },
  { "id": 50, "name": "C (GCC 9.2.0)", "mode": "clike", "mime": "text/x-csrc" },
  { "id": 54, "name": "C++ (GCC 9.2.0)", "mode": "clike", "mime": "text/x-c++src" },
  { "id": 86, "name": "Clojure (1.10.1)", "mode": "clojure", "mime": "text/x-clojure" },
  { "id": 51, "name": "C# (Mono 6.6.0.161)", "mode": "clike", "mime": "text/x-csharp" },
  { "id": 77, "name": "COBOL (GnuCOBOL 2.2)", "mode": "cobol", "mime": "text/x-cobol" },
  { "id": 55, "name": "Common Lisp (SBCL 2.0.0)", "mode": "commonlisp", "mime": "text/x-common-lisp" },
  { "id": 90, "name": "Dart (2.19.2)", "mode": "dart", "mime": "application/dart" },
  { "id": 56, "name": "D (DMD 2.089.1)", "mode": "d", "mime": "text/x-d" },
  { "id": 57, "name": "Elixir (1.9.4)", "mode": "elixir", "mime": "text/x-elixir" },
  { "id": 58, "name": "Erlang (OTP 22.2)", "mode": "erlang", "mime": "text/x-erlang" },
  { "id": 44, "name": "Executable", "mode": "null", "mime": "text/plain" },
  { "id": 87, "name": "F# (.NET Core SDK 3.1.202)", "mode": "mllike", "mime": "text/x-fsharp" },
  { "id": 59, "name": "Fortran (GFortran 9.2.0)", "mode": "fortran", "mime": "text/x-fortran" },
  { "id": 60, "name": "Go (1.13.5)", "mode": "go", "mime": "text/x-go" },
  { "id": 95, "name": "Go (1.18.5)", "mode": "go", "mime": "text/x-go" },
  { "id": 88, "name": "Groovy (3.0.3)", "mode": "groovy", "mime": "text/x-groovy" },
  { "id": 61, "name": "Haskell (GHC 8.8.1)", "mode": "haskell", "mime": "text/x-haskell" },
  { "id": 96, "name": "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)", "mode": "clike", "mime": "text/x-java" },
  { "id": 91, "name": "Java (JDK 17.0.6)", "mode": "clike", "mime": "text/x-java" },
  { "id": 62, "name": "Java (OpenJDK 13.0.1)", "mode": "clike", "mime": "text/x-java" },
  { "id": 63, "name": "JavaScript (Node.js 12.14.0)", "mode": "javascript", "mime": "application/javascript" },
  { "id": 93, "name": "JavaScript (Node.js 18.15.0)", "mode": "javascript", "mime": "application/javascript" },
  { "id": 97, "name": "JavaScript (Node.js 20.17.0)", "mode": "javascript", "mime": "application/javascript" },
  { "id": 102, "name": "JavaScript (Node.js 22.08.0)", "mode": "javascript", "mime": "application/javascript" },
  { "id": 78, "name": "Kotlin (1.3.70)", "mode": "clike", "mime": "text/x-kotlin" },
  { "id": 64, "name": "Lua (5.3.5)", "mode": "lua", "mime": "text/x-lua" },
  { "id": 89, "name": "Multi-file program", "mode": "null", "mime": "text/plain" },
  { "id": 79, "name": "Objective-C (Clang 7.0.1)", "mode": "clike", "mime": "text/x-objectivec" },
  { "id": 65, "name": "OCaml (4.09.0)", "mode": "mllike", "mime": "text/x-ocaml" },
  { "id": 66, "name": "Octave (5.1.0)", "mode": "octave", "mime": "text/x-octave" },
  { "id": 67, "name": "Pascal (FPC 3.0.4)", "mode": "pascal", "mime": "text/x-pascal" },
  { "id": 85, "name": "Perl (5.28.1)", "mode": "perl", "mime": "text/x-perl" },
  { "id": 68, "name": "PHP (7.4.1)", "mode": "php", "mime": "text/x-php" },
  { "id": 98, "name": "PHP (8.3.11)", "mode": "php", "mime": "text/x-php" },
  { "id": 43, "name": "Plain Text", "mode": "null", "mime": "text/plain" },
  { "id": 69, "name": "Prolog (GNU Prolog 1.4.5)", "mode": "prolog", "mime": "text/x-prolog" },
  { "id": 70, "name": "Python (2.7.17)", "mode": "python", "mime": "text/x-python" },
  { "id": 92, "name": "Python (3.11.2)", "mode": "python", "mime": "text/x-python" },
  { "id": 100, "name": "Python (3.12.5)", "mode": "python", "mime": "text/x-python" },
  { "id": 71, "name": "Python (3.8.1)", "mode": "python", "mime": "text/x-python" },
  { "id": 80, "name": "R (4.0.0)", "mode": "r", "mime": "text/x-rsrc" },
  { "id": 72, "name": "Ruby (2.7.0)", "mode": "ruby", "mime": "text/x-ruby" },
  { "id": 99, "name": "Rust (1.68.1)", "mode": "rust", "mime": "text/x-rustsrc" },
  { "id": 101, "name": "Rust (1.72.1)", "mode": "rust", "mime": "text/x-rustsrc" },
  { "id": 73, "name": "Rust (1.40.0)", "mode": "rust", "mime": "text/x-rustsrc" },
  { "id": 81, "name": "Scala (2.13.2)", "mode": "clike", "mime": "text/x-scala" },
  { "id": 82, "name": "SQL (SQLite 3.27.2)", "mode": "sql", "mime": "text/x-sql" },
  { "id": 83, "name": "Swift (5.2.1)", "mode": "swift", "mime": "text/x-swift" },
  { "id": 84, "name": "TypeScript (3.7.4)", "mode": "javascript", "mime": "application/typescript" },
  { "id": 94, "name": "TypeScript (4.9.5)", "mode": "javascript", "mime": "application/typescript" }
]
;

export const codeMirrorThemes = [
  { name: "3024 Day", theme: "3024-day" },
  { name: "3024 Night", theme: "3024-night" },
  { name: "ABCDEF", theme: "abcdef" },
  { name: "Ambiance", theme: "ambiance" },
  { name: "Ambiance Mobile", theme: "ambiance-mobile" },
  { name: "Base16 Dark", theme: "base16-dark" },
  { name: "Base16 Light", theme: "base16-light" },
  { name: "Bespin", theme: "bespin" },
  { name: "Blackboard", theme: "blackboard" },
  { name: "Cobalt", theme: "cobalt" },
  { name: "Colorforth", theme: "colorforth" },
  { name: "Darcula", theme: "darcula" },
  { name: "Dracula", theme: "dracula" },
  { name: "Duotone Dark", theme: "duotone-dark" },
  { name: "Duotone Light", theme: "duotone-light" },
  { name: "Eclipse", theme: "eclipse" },
  { name: "Elegant", theme: "elegant" },
  { name: "Erlang Dark", theme: "erlang-dark" },
  { name: "Gruvbox Dark", theme: "gruvbox-dark" },
  { name: "Hopscotch", theme: "hopscotch" },
  { name: "Icecoder", theme: "icecoder" },
  { name: "Idea", theme: "idea" },
  { name: "Isotope", theme: "isotope" },
  { name: "Lesser Dark", theme: "lesser-dark" },
  { name: "Liquibyte", theme: "liquibyte" },
  { name: "Lucario", theme: "lucario" },
  { name: "Material", theme: "material" },
  { name: "Material Darker", theme: "material-darker" },
  { name: "Material Ocean", theme: "material-ocean" },
  { name: "Material Palenight", theme: "material-palenight" },
  { name: "MBO", theme: "mbo" },
  { name: "MDN-Like", theme: "mdn-like" },
  { name: "Midnight", theme: "midnight" },
  { name: "Monokai", theme: "monokai" },
  { name: "Moxer", theme: "moxer" },
  { name: "Neat", theme: "neat" },
  { name: "Neo", theme: "neo" },
  { name: "Night", theme: "night" },
  { name: "Nord", theme: "nord" },
  { name: "Panda Syntax", theme: "panda-syntax" },
  { name: "Paraiso Dark", theme: "paraiso-dark" },
  { name: "Paraiso Light", theme: "paraiso-light" },
  { name: "Pastel on Dark", theme: "pastel-on-dark" },
  { name: "Railscasts", theme: "railscasts" },
  { name: "Rubyblue", theme: "rubyblue" },
  { name: "Seti", theme: "seti" },
  { name: "Shadowfox", theme: "shadowfox" },
  { name: "Solarized Dark", theme: "solarized dark" },
  { name: "Solarized Light", theme: "solarized light" },
  { name: "The Matrix", theme: "the-matrix" },
  { name: "Tomorrow Night Bright", theme: "tomorrow-night-bright" },
  { name: "Tomorrow Night Eighties", theme: "tomorrow-night-eighties" },
  { name: "TTCN", theme: "ttcn" },
  { name: "Twilight", theme: "twilight" },
  { name: "Vibrant Ink", theme: "vibrant-ink" },
  { name: "XQ Dark", theme: "xq-dark" },
  { name: "XQ Light", theme: "xq-light" },
  { name: "Yeti", theme: "yeti" },
  { name: "Zenburn", theme: "zenburn" }
];

